name: Review pull request

on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review_pull_request:
    if: github.event.pull_request.draft == false
    name: CI
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 30
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up signing properties
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
        run: |
          echo -e $SIGNING_PROPERTIES | base64 -d > signing.properties 

      - name: Set up Google Services json
        env:
          FIREBASE_GOOGLE_SERVICES_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
        run: |
          echo -e $FIREBASE_GOOGLE_SERVICES_JSON | base64 -d > app/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Run unit tests with Kover
        run: ./gradlew koverXmlReport

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bundle exec danger
